name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    environment: dev
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env: 
        USERNAME: ${{ secrets.CI_USERNAME }}
        BASE_URL: ${{ secrets.CI_BASE_URL }}
        PASSWORD: ${{ secrets.CI_PASSWORD }}
        API_KEY: ${{ secrets.CI_API_KEY }}
        API_BASE_URL: ${{ secrets.CI_API_BASE_URL }}
    - name: Set timestamp
      id: timestamp
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        TIMESTAMP=$(TZ='Europe/Stockholm' date +'%Y-%m-%d_%H-%M-%S')
        BRANCH=$(echo "${{ github.ref_name }}" | tr '/' '-')
        echo "value=${BRANCH}-build${{ github.run_number }}-${SHORT_SHA}_${TIMESTAMP}" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: Testrapport-${{ steps.timestamp.outputs.value }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Pages artifacts
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report
      
    - name: deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4
